/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CustomerRegistration: typeof import('./components/Customer/ManageCustomer.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MainContent: typeof import('./components/MainContent.vue')['default']
    ManageCustomer: typeof import('./components/Customer/ManageCustomer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/SideBar.vue')['default']
    ViewCustomers: typeof import('./components/Customer/ViewCustomers.vue')['default']
  }
}
