/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/mainContent/RegisterCustomer': RouteRecordInfo<'/mainContent/RegisterCustomer', '/mainContent/RegisterCustomer', Record<never, never>, Record<never, never>>,
    '/mainContent/ViewCustomers': RouteRecordInfo<'/mainContent/ViewCustomers', '/mainContent/ViewCustomers', Record<never, never>, Record<never, never>>,
    '/MainContent/RegisterCustomer': RouteRecordInfo<'/MainContent/RegisterCustomer', '/MainContent/RegisterCustomer', Record<never, never>, Record<never, never>>,
    '/MainContent/ViewCustomers': RouteRecordInfo<'/MainContent/ViewCustomers', '/MainContent/ViewCustomers', Record<never, never>, Record<never, never>>,
  }
}
