/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '//customer/Manage': RouteRecordInfo<'//customer/Manage', '/customer/Manage', Record<never, never>, Record<never, never>>,
    '//customer/Register': RouteRecordInfo<'//customer/Register', '/customer/Register', Record<never, never>, Record<never, never>>,
    '//Design': RouteRecordInfo<'//Design', '/Design', Record<never, never>, Record<never, never>>,
    '//orders/Booking': RouteRecordInfo<'//orders/Booking', '/orders/Booking', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
  }
}
